[versions]
checkerframework = "3.37.0"
netty = "4.1.101.Final"
jackson = "2.18.0"
junit = "5.9.2"

[libraries]
checker-qual = { group = "org.checkerframework", name = "checker-qual", version.ref = "checkerframework" }
fastutil-bom = { group = "org.cloudburstmc.fastutil", name = "bom", version = "8.5.15" }
fastutil-long-common = { group = "org.cloudburstmc.fastutil.commons", name = "long-common" }
fastutil-long-object-maps = { group = "org.cloudburstmc.fastutil.maps", name = "long-object-maps" }
fastutil-int-object-maps = { group = "org.cloudburstmc.fastutil.maps", name = "int-object-maps" }
fastutil-object-int-maps = { group = "org.cloudburstmc.fastutil.maps", name = "object-int-maps" }

netty-buffer = { group = "io.netty", name = "netty-buffer", version.ref = "netty" }
netty-transport-raknet = { group = "org.cloudburstmc.netty", name = "netty-transport-raknet", version = "1.0.0.CR3-20260421.213623-35" }

jackson-annotations = { group = "com.fasterxml.jackson.core", name = "jackson-annotations", version.ref = "jackson" }
jose4j = { group = "org.bitbucket.b_c", name = "jose4j", version = "0.9.6" }
natives = { group = "com.nukkitx", name = "natives", version = "1.0.3" }
math = { group = "org.cloudburstmc.math", name = "immutable", version = "2.0-20220327.162752-1" }
nbt = { group = "org.cloudburstmc", name = "nbt", version = "3.0.4.Final" }

snappy = { group = "io.airlift", name = "aircompressor", version = "0.27" }

junit = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher", version = "1.9.2" }

[plugins]
lombok = { id = "io.freefair.lombok", version = "9.2.0" }
publish = { id = "com.vanniktech.maven.publish", version = "0.36.0" }
